portfolio/interviewapp/urls.py
from django.urls import path
from . import views
app_name = 'intapp'
urlpatterns = [
    path('', views.Choose_Month, name='choose_month'),
    path('createint',views.createinterview,name='createint'),
    path('inthome/<int:month>', views.IntDesciption, name='inthome'),
    path('export_to_excel',views.export_to_excel,name='export_to_excel'),
    
]

portfolio/loginapp/urls.py
from django.urls import path
from . import views
app_name = 'loginapp'
urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.login_page, name='login'),
    path('logout', views.logout_page, name='logout'),
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('loginapp/', include('loginapp.urls')),
    path('', include('interviewapp.urls'))
]
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/interviewapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator

# Create your models here.
class Interview(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_interview')
    date = models.DateField(blank=False)
    activities = models.TextField(blank=True)
    no_of_Hours = models.PositiveIntegerField(blank=False)
    positon_of_interviewd_person = models.CharField(max_length=500,blank=False)
    marks = models.PositiveIntegerField(blank=False,validators=[MaxValueValidator(10),MinValueValidator(0)])
    comments = models.TextField(blank=True)
    attachments = models.FileField(upload_to='attachments',blank=True)
    refer = models.BooleanField(default=False)

    def __str__(self):
        return ('{}'.format(self.date))

portfolio/loginapp/models.py
from django.db import models

# Create your models here.

portfolio/interviewapp/forms.py
from django import forms
from .models import Interview


class Create_Interview_Form(forms.ModelForm):
  
    class Meta:
        model = Interview
        exclude = ('user',)
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

portfolio/loginapp/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    captcha = CaptchaField()
    class Meta:
        model = User
        fields = ('username','password1','password2','email',)
        # fields = "__all__"

portfolio/interviewapp/views.py
import pandas as pd
from django.shortcuts import render
from datetime import datetime
from django.shortcuts import render,HttpResponseRedirect
from django.urls import reverse
from .forms import Create_Interview_Form
from django.contrib import messages
from django.views.generic import ListView
from .models import Interview
from django.contrib.auth.decorators import login_required
from calendar import month_name
import pandas as pd
# Create your views here.

@login_required(login_url='loginapp:login')
def createinterview(request):
    form = Create_Interview_Form
    if request.method == 'POST':
        form = Create_Interview_Form(request.POST)
        if form.is_valid():
            intboi = form.save(commit=False)
            intboi.user = request.user
            intboi.save()
            messages.success(request,'Added Your Interview!')
            return HttpResponseRedirect(reverse('intapp:choose_month'))
    
    dict = {'form':form}
    return render(request,'intapp/createint.html',dict)


@login_required(login_url='loginapp:login')
def IntDesciption(request,month):
    # now = datetime.now()
    # month = now.month
    this_month = month_name[month]
    interviews = Interview.objects.filter(user=request.user,date__month=month)
    count = Interview.objects.filter(user=request.user,date__month=month).count()
    return render(request, 'intapp/intdescription.html', {'interviews': interviews, 'month': month,'count':count,'this_month':this_month})


@login_required(login_url='loginapp:login')
def Choose_Month(request):
    return render(request,'intapp/choose_month.html')



def export_to_excel(request):
    interviews = Interview.objects.all()
    data = {
        'Serial Number': [i.id for i in interviews],
        'Date': [i.date for i in interviews],
        'Activities': [i.activities for i in interviews],
        'Numbers/Hours': [i.no_of_Hours for i in interviews],
        'Position of Interviewed Person': [i.positon_of_interviewd_person for i in interviews],
        'Marks (out of 10)': [i.marks for i in interviews],
        'Comments': [i.comments for i in interviews],
        'Attachments': [i.attachments.url if i.attachments else 'No CV' for i in interviews],
        'Refer': ['Yes' if i.refer else 'No' for i in interviews]
    }
    df = pd.DataFrame(data)
    df.to_csv('interviews.csv', index=False)
    messages.success(request,'Successfully Exported To Excel!')
    return render(request, 'intapp/intdescription.html', {'interviews': interviews})

portfolio/loginapp/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect,redirect
from django.contrib.auth import login,logout,authenticate
from django.urls import reverse
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

# Create your views here.

def signup(request):
    form = SignUpForm
    if request.method =='POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('loginapp:login'))

    dict = {'form':form}
    return render(request,'loginapp/signup.html',dict)        


def login_page(request):
    form = AuthenticationForm
    if request.method =='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                messages.success(request,'Logged In Successfully!')
                return HttpResponseRedirect(reverse('intapp:choose_month'))

    dict = {'form':form}
    return render(request,'loginapp/login.html',dict)        

def logout_page(request):
    logout(request)
    messages.warning(request,'Logged Out!')
    return HttpResponseRedirect(reverse('loginapp:login'))

portfolio/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block titleblock%} {%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>

    {%include 'navbar.html'%}


    <!-- THESE ARE ONLY FOR DISPLAYING MESSAGES i.e for updating profile,loggin out etc -->
    <div class="container" style="padding-top:20px">
        <div class="messages container mt-2">
            {%if messages%}
            {%for message in messages%}
            <div {%if message.tags%} class="alert alert-{{message.tags}}" {%endif%} role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss=""="alert" aria-level="Close">
                    <span aria-hidden="true">
                        &times;

                    </span>

                </button>




            </div>

            {%endfor%}

            {%endif%}



            {%block bodyblock%} {%endblock%}

</body>

<style>
    body{
        background-color: lightgray;
    }
</style>

</html>

portfolio/templates/intapp/choose_month.html
{%extends 'base.html'%}

{%block titleblock%}
Monthly Reports
{%endblock%}


{%block bodyblock%}
<h1><b><u>Montly Report Sheets : </u></b> </h1>
<br>
<br>
<table class="table table-bordered border-dark" style="height: 100%;">
    <tbody style="height: 100%;">
        <tr>
            <th scope="col"><h3><a href="{%url 'intapp:inthome' month=1%}">January</a></h3></th>
            <th scope="col"><h3><a href="{%url 'intapp:inthome' month=2%}">Febraury</a></h3></th>
            <th scope="col"><h3><a href="{%url 'intapp:inthome' month=3%}">March</a></h3></th>
        </tr>
        <tr>
            <td><h3><a href="{%url 'intapp:inthome' month=4%}">April</a></h3></td>
            <td><h3><a href="{%url 'intapp:inthome' month=5%}">May</a></h3></h3></td>
            <td><h3><a href="{%url 'intapp:inthome' month=6%}">June</a></h3></td>

        </tr>
        <tr>
            <td><h3><a href="{%url 'intapp:inthome' month=7%}">July</a></h3></td>
            <td><h3><a href="{%url 'intapp:inthome' month=8%}">August</a></h3></td>
            <td><h3><a href="{%url 'intapp:inthome' month=9%}">September</a></h3></td>
        </tr>
        <tr>
            <td><h3><a href="{%url 'intapp:inthome' month=10%}">October</a></h3></td>
            <td><h3><a href="{%url 'intapp:inthome' month=11%}">November</a></h3></td>
            <td><h3><a href="{%url 'intapp:inthome' month=12%}">December</a></h3></td>
        </tr>
    </tbody>
</table>


{%endblock%}

portfolio/templates/intapp/createint.html
{%extends 'base.html'%}

{%block titleblock%}
Create Interview
{%endblock%}

{%block bodyblock%}

<h2>Add Your Interview </h2>
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn btn-outline-success" type="submit">Add!</button>



</form>
<br>

{%endblock%}

portfolio/templates/intapp/intdescription.html
{% extends 'base.html' %}

{%block titleblock%}
Interview Home
{%endblock%}
{%block bodyblock%}



<h1> <u><i><b>Interviews for month of {{ this_month }}</b></i></u> </h1>
<br>

<a href="{%url 'intapp:export_to_excel'%}"><button class="btn btn-outline-dark"> Export To Excel</button> </a>
<br>
<br>
<br>
<table  class="table table-bordered border-success" >
    <thead style="height: 500%;">
        <tr>
            <th scope="col">Serail Number:</th>
            <th scope="col">Date</th>
            <th scope="col"><h1>Activities</h1></th>
            <th scope="col">Numbers/Hours</th>
            <th scope="col">Position of Interviewed Person</th>
            <th scope="col">Marks (out of 10)</th>
            <th scope="col"><h1>Comments</h1></th>
            <th scope="col">Attachments</th>
            <th scope="col">Refer</th>
        </tr>
    </thead>
    <tbody style="height: 500%;">
        {% for interview in interviews %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ interview.date }}</td>
            <td style="width: 30%;">{{ interview.activities }}</td>
            <td >{{ interview.no_of_Hours }}</td>
            <td>{{ interview.positon_of_interviewd_person }}</td>
            <td>{{ interview.marks }}</td>
            <td style="width: 100%;">{{ interview.comments }}</td>
            {%if interview.attachments%}
            <td><a href="{{ interview.attachments.url }}">CV</a></td>
            {%else%}
            <td>No Cv</td>
            {%endif%}
            {%if interview.refer%}
            <td>Yes</td>
            {%else%}
            <td>No</td>
            {%endif%}

        </tr>
        {% endfor %}
    </tbody>
</table>
<br>
<h3><b>Total Interviews Done In This Month : {{count}}</b></h3>







{%endblock%}

portfolio/templates/intapp/search.html
{%extends 'base.html'%}

{%block titleblock%}
Searched Results
{%endblock%}

{%block bodyblock%}

{%for searched_result in searched_results%}
<h1> Interviews for month of {{ this_month }} </h1>
<table class="table table-bordered border-success">
    <thead>
        <tr>
            <th scope="col">Serail Number:</th>
            <th scope="col">Date</th>
            <th scope="col">Activities</th>
            <th scope="col">No of Hours</th>
            <th scope="col">Position of Interviewed Person</th>
            <th scope="col">Marks</th>
            <th scope="col">Comments</th>
            <th scope="col">Attachments</th>
            <th scope="col">Refer</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ searched_result.date }}</td>
            <td>{{ searched_result.activities }}</td>
            <td>{{ searched_result.no_of_Hours }}</td>
            <td>{{ searched_result.positon_of_interviewd_person }}</td>
            <td>{{ searched_result.marks }}</td>
            <td>{{ interview.comments }}</td>
            {%if searched_result.attachments%}
            <td><a href="{{ searched_result.attachments.url }}">CV</a></td>
            {%else%}
            <td>No Cv</td>
            {%endif%}
            {%if searched_result.refer%}
            <td>Yes</td>
            {%else%}
            <td>No</td>
            {%endif%}

        </tr>
        {% endfor %}
    </tbody>
</table>

<h3>Total Interviews Done In This Month : {{count}}</h3>
{%endblock%}

portfolio/templates/loginapp/login.html
{%extends 'base.html'%}

{%block titleblock%}
LOGIN PAGE
{%endblock%}

{%block bodyblock%}

<h2>LOGIN IN YOUR ACCOUNT: </h2>
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn btn-outline-success" type="submit">Login</button>



</form>
<br>
<a href="{%url 'loginapp:signup'%}">Don`t Have An Account?</a>
{%endblock%}

portfolio/templates/loginapp/signup.html
{%extends 'base.html'%}

{%block titleblock%}
Sign Up Page
{%endblock%}

{%block bodyblock%}

<h2>CREATE AN ACCOUNT! </h2>
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button  class="btn btn-outline-success"  type="submit">Sign Up</button>



</form>
<br>
<a href="{%url 'loginapp:login'%}">Have an Account?</a>
{%endblock%}

portfolio/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Interview Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {%if user.is_authenticated%}
                <li class="nav-item">
                    <a class="nav-link active" href="{%url 'intapp:choose_month'%}">All Interviews</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'intapp:createint'%}">Create  New Interview</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'loginapp:logout'%}">Logout</a>
                </li>
                {%else%}
                <li class="nav-item">
                    <a href="{%url 'loginapp:login'%}"   class="nav-link">Login</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'loginapp:signup'%}" class="nav-link">Sign Up</a>
                </li>
                {%endif%}
            </ul>
        </div>
    </div>
</nav>